name: repo site generator

on:
  push:
    branches:
      - main
  schedule:
    - cron: 41 */3 * * *
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Cache package manifests
        uses: actions/cache@v2
        env:
          cache-name: cache-package-manifests
        with:
          path: ./cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/*') }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: python3 -m pip install -r ./requirements.txt

      - name: Generate repository data
        run: python3 -m repogen -i ./packages -o ./content -D -L

      - name: Generate site content
        run: invoke build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
